/**
 * lib/revenue.ts
 *
 * Analytics and Revenue Tracking module.
 *
 * Uses supabaseAdmin to bypass RLS and aggregate revenue from bookings.
 * Note: Only 'confirmed', 'pending', and 'reschedule_requested' bookings
 * count towards revenue. 'cancelled' bookings do not generate revenue.
 */

import { supabaseAdmin } from "@/lib/supabaseClient";

/**
 * Common booking statuses that represent active (paying) bookings.
 */
const ACTIVE_STATUSES = ["confirmed", "pending", "reschedule_requested"];

/**
 * Returns the total revenue for a specific day.
 * @param date ISO Date string (YYYY-MM-DD)
 * @returns Total revenue in IDR (integer)
 */
export async function getDailyRevenue(date: string): Promise<number> {
  const { data, error } = await supabaseAdmin
    .from("bookings")
    .select("service_price")
    .in("status", ACTIVE_STATUSES)
    .eq("date", date);

  if (error) {
    console.error("[getDailyRevenue] failed:", error.message);
    return 0;
  }

  return data.reduce((sum, row) => sum + (row.service_price || 0), 0);
}

/**
 * Returns the total revenue for a specific month.
 * @param month YYYY-MM string (e.g., "2026-04")
 * @returns Total revenue in IDR (integer)
 */
export async function getMonthlyRevenue(month: string): Promise<number> {
  // To get monthly revenue efficiently, we match dates starting with YYYY-MM
  const { data, error } = await supabaseAdmin
    .from("bookings")
    .select("service_price")
    .in("status", ACTIVE_STATUSES)
    .like("date", `${month}-%`);

  if (error) {
    console.error("[getMonthlyRevenue] failed:", error.message);
    return 0;
  }

  return data.reduce((sum, row) => sum + (row.service_price || 0), 0);
}

/**
 * Returns the all-time total revenue generated by the barbershop.
 * @returns Total revenue in IDR (integer)
 */
export async function getTotalRevenue(): Promise<number> {
  const { data, error } = await supabaseAdmin
    .from("bookings")
    .select("service_price")
    .in("status", ACTIVE_STATUSES);

  if (error) {
    console.error("[getTotalRevenue] failed:", error.message);
    return 0;
  }

  return data.reduce((sum, row) => sum + (row.service_price || 0), 0);
}
